### ISSUE TITLE
Funding an account in a unit test?

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [web3j/web3j-unit#41]
Was trying to figure out a way to test a deposit contract that I am working with, and am getting stumped on **how** to actually spin up an embedded node with a funded wallet

I'm using a quick helper to give me a generated `Credentials` object 

```kotlin
fun generateCreds(): Credentials {
    val password = UUID.randomUUID().toString()
    val walletDirectory = createTempDir()
    val wallet = WalletUtils.generateNewWalletFile(password, walletDirectory)
    return WalletUtils.loadCredentials(password, File("$walletDirectory/$wallet"))
}
```

However, this account obviously has a 0 balance... I see there is a way through the genesis file to prefund an address, and I *suppose* it would be possible to generate a wallet, dictate the desired genesis funding, and then load that wallet explicitly, but I'm wondering if there is a more elegant way that I am missing

**Comment by xaviarias** [comment]
Hi, you can load the default credentials using:

```Credentials.create("0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63")```
 
They are also used in the injected transaction manager so should have some funds already.

**Comment by rgbrizzlehizzle** [comment]
Hmmm ok that definitely works so I'm going to close this, but for my understanding, a couple questions 

1. Why this account? Is it just a random account that was chosen to be prefunded somewhere inside the repo? 
2. As per the injected TM, that had me a bit confused b/c I *had* been looking into trying to use `web3j.ethAccounts()` but when I `send()` that request it throws an unsupported op exception... could you expand a bit on *how* one would go about getting a set of accounts that are prefunded? IE something like in ganache when you spin up a daemon it provides you with 10 prefunded addresses

**Comment by rgbrizzlehizzle** [comment]
Right now just running with a simple `fundAccount` method to transfer from the preseed to any account I generate, but would be cool to just be able to get a set of preseeded accounts to start 

```kotlin
object TestUtils {

  private val papaAccount = Credentials.create("0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63")

  fun generateCreds(): Credentials {
    val password = UUID.randomUUID().toString()
    val walletDirectory = createTempDir()
    val wallet = WalletUtils.generateNewWalletFile(password, walletDirectory)
    return WalletUtils.loadCredentials(password, File("$walletDirectory/$wallet"))
  }

  /**
   * Amount in ETHER to send to account
   */
  fun fundAccount(address: String, amount: BigDecimal, web3j: Web3j) {
    Transfer.sendFunds(web3j, papaAccount, address, amount, Convert.Unit.ETHER).send()
  }

}
```

**Comment by xaviarias** [comment]
> Hmmm ok that definitely works so I'm going to close this, but for my understanding, a couple questions
> 
> 1. Why this account? Is it just a random account that was chosen to be prefunded somewhere inside the repo?

Yes is just a random account, maybe you can get more information on the [Web3j EVM](https://github.com/web3j/web3j-evm) project.

> 2. As per the injected TM, that had me a bit confused b/c I _had_ been looking into trying to use `web3j.ethAccounts()` but when I `send()` that request it throws an unsupported op exception... could you expand a bit on _how_ one would go about getting a set of accounts that are prefunded? IE something like in ganache when you spin up a daemon it provides you with 10 prefunded addresses

I'm not sure, but most likely not all `eth_` JSON RPC methods are supported in Web3j EVM, because is an embedded VM more intended to run smart contracts than to support a full-fledged node API.

**Comment by rgbrizzlehizzle** [comment]
> Yes is just a random account, maybe you can get more information on the Web3j EVM project.

Ahh fantastic will check it out

> most likely not all eth_ JSON RPC methods are supported in Web3j EVM

I see I think I was misinterpreting the intended purpose of `web3j.ethAccounts()`

Appreciate the help 🙏
