### ISSUE TITLE
Container GETH does not start

### ISSUE THREAD

**Issue by saulgiordani** [web3j/web3j-unit#58]
# EVMTest nodetype GETH not working
I'm trying to run an integration test with @EVMTest(type = NodeType.GETH, version = "stable") annotation, but as soon as the ethereum-go container starts, it stops.

In the container logs I can see the message

Fatal: keyfile must be given as the only argument
Incorrect Usage. flag provided but not defined: -rpc

## Steps To Reproduce
Run a test in a class annotated with @EVMTest(type = NodeType.GETH

### Expected behavior
Container should spin up

### Actual behavior
It doesn't

## Environment
- Web3j version: 4.9.6
- Java 17
- Mac os

**Comment by NickSneo** [comment]
Fix merged
